import { Application } from '@hotwired/stimulus';
import ResponsiveNavMenu from "./controllers/responsive_nav_menu";
import Wishlist from "./controllers/wishlist";
import Filter from "./controllers/filter";
import Cart from "./controllers/cart";
import lineItemQuantity from "./controllers/lineItemQuantity";
import Order from "./controllers/order";
import DeleteAccount from "./controllers/deleteAccount";
import Sidebar from "./controllers/sidebar";
import Tree from "./controllers/categoriesTree";
import disableButton from "./controllers/disableButton";

const application = Application.start();
application.register("responsive-nav-menu", ResponsiveNavMenu);
application.register("wishlist", Wishlist);
application.register("cart", Cart);
application.register("filter", Filter);
application.register("lineItemQuantity", lineItemQuantity);
application.register("order", Order);
application.register("delete-account", DeleteAccount);
application.register("sidebar", Sidebar);
application.register("tree", Tree);
application.register("disableButton", disableButton);
